# Chapter 1

导入基础依赖

In [2]:
import collections
import hashlib
import math
import os
import random
import re
import shutil
import sys
import tarfile
import time
import zipfile
from collections import defaultdict
import pandas as pd
import requests
from IPython import display
from matplotlib import pyplot as plt
from matplotlib_inline import backend_inline
    
d2l = sys.modules[__name__]

导入基础组件：

In [3]:
from mxnet import np, npx
npx.set_np()

创建张量：

In [4]:
x = np.arange(12)
x

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

查看张量形状：

In [5]:
x.shape

(12,)

张量中元素的总数，即形状的所有元素乘积，可以检查它的大小：

In [6]:
x.size

12

改变一个张量的形状而不改变元素数量和元素值，可以调用reshape函数:

In [7]:
X = x.reshape(3, 4)
X

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

可以通过-1来调用此自动计算出维度的功能，如：

In [9]:
x.reshape(-1,3)

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

初始化全0张量：

In [11]:
np.zeros((2, 3, 4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

初始化全1张量：

In [12]:
np.ones((2, 3, 4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

从某个特定的概率分布中随机采样来得到张量中每个元素的值。如：每个元素都从均值为0、标准差为1的标准高斯分布（正态分布）中随机采样：

In [13]:
np.random.normal(0, 1, size=(3, 4))

array([[ 1.1630785 ,  2.2122061 ,  0.4838046 ,  0.7740038 ],
       [ 0.29956347,  1.0434403 ,  0.15302546,  1.1839255 ],
       [-1.1688148 ,  1.8917114 ,  1.558071  , -1.2347414 ]])

使用Python列表创建张量：

In [14]:
np.array([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

array([[2., 1., 4., 3.],
       [1., 2., 3., 4.],
       [4., 3., 2., 1.]])